---
name: String-Expand
version: 0.03
author:
  - 'Paul Evans E<lt>leonerd@leonerd.org.ukE<gt>'
abstract: |-
  string utility functions for expanding variables in
  self-referential sets
license: perl
build_requires:
  Test::Exception: 0
  Test::More: 0
provides:
  String::Expand:
    file: lib/String/Expand.pm
    version: 0.03
generated_by: Module::Build version 0.26
